### PR TITLE
added option :fixed_top_left to prevent the header row and the first …

### PR DESCRIPTION
**Pull request by MadBomber**
…column from scrolling in an xlsx file.  This new option is part of the :header_style option hash.

This is the basic idea. It works.  You may have a better feel for the actual style name to use that fits better within your sense of an API element.

Solves #25

### CODE REVIEW

**Comment by westonganger** [comment]
The new options should probably be called `fixed: true` or `freeze: true`

One problem I see with the implementation is that it specifies B2 as the start, this does not take into account headers with multiple rows. Also should this not be B1?

I would like to see this generalized and made available fior custom usage. But that could be left till later.

**Comment by MadBomber** [comment]
> The new option should probably be called fixed: true or freeze: true
I agree these option names are better.  I'm thinking that instead of a Boolean, they should accept a cell reference in order to be more generic.  For example:

- `freeze: A` to fix column A in place
- `freeze: 1` to fix row 1 in place
- `freeze: A1` to fix both column A and row 1 in place
- `freeze: B` to fix both column A and B in place
- `freeze: 2` to fix both row 1 and row 2 in place
- `freeze: B2` to fix both row 1 and 2 and columns A and B in place

After writing that description I'm not so sure.  Consider this as an alternative:

If the option name were `scroll_from: <cell reference>` that would mean that the first scrolling area top-left cell would be the `<cell reference>`

Using the `scroll_from: <cell reference>` idea would make for a simpler implementation.

With this option `scroll_from: b2` would fix column A and row 1 in place.  `scroll_from: B1` would only fix column A in place.  `scroll_from: A2` would fix row 1 in place.  `scroll_from: A3` would fix row 1 and row 2 in place.... etc.

**Comment by westonganger** [comment]
While `scroll_from` makes sense its a new term. I really want to use the term `freeze` because that is the term they use in MS Excel or Libreoffice Calc

I would like the syntax to be: 

- `freeze: {row: 'B', column: '2'}`
- `freeze: {row: 2, column: '2'}`

Also I would like the option `freeze_header: true` as a shortcut to freeze the whole header.

**Comment by westonganger** [comment]
I have started the implementation of this on the `xlsx_freeze` branch. But it should be noted this feature is limited to the unreleased v3.0.0 / master of Axlsx

**Comment by MadBomber** [comment]
I just saw the community version caxlsx released at version 3.0.1.  Do you
intend to move spreadsheet_architecture to use caxlsx?

The reason I was looking at SA again was that I had a need to add some
borders to cells in some new xlsx reports.  I could not get it to work.
Even the unit tests in SA do not have borders working.

Dewayne
  o-*

**Comment by westonganger** [comment]
Please create a separate issue for each item, that being said I hadnt heard of caxlsx but would love to support it.

**Comment by westonganger** [comment]
Borders were broken in v3.2.1. I have now released v3.3.0 includes the fix for borders.

**Comment by westonganger** [comment]
The freeze functionality has now been implemented in master. Closing

**Pull request closed without merging**
